#!/usr/bin/env python
#
# Copyright (c) 2015 SUSE LLC. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# infile format:
# array of management node definitions
#
# [
#  { 'name': 'vCenter.domain.top',
#    'type': 'vCenter',
#    'host': 'vCenter.domain.top',
#    'port': 443,
#    'user': 'admin',
#    'pass': 'password'
#  },
#  { ... }
# ]

import sys
sys.path.append('./lib')
from gatherer.gatherer import Gatherer, parseOptions

# Start program
if __name__ == "__main__":
    try:
        opts = parseOptions()
        g = Gatherer(opts).main()
    except Exception as ex:
        sys.stderr.write("General error: {0}\n".format(ex))
        if opts.verbose > 0:
            raise
        sys.exit(1)
sys.exit(0)
